// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCrmUser = "crm_users"

// CrmUser mapped from table <crm_users>
type CrmUser struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email       string `gorm:"column:email;not null" json:"email"`
	Phone       string `gorm:"column:phone;not null" json:"phone"`
	Username    string `gorm:"column:username;not null" json:"username"`
	Password    string `gorm:"column:password;not null" json:"password"`
	CreatedAt   int32  `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   int32  `gorm:"column:updated_at" json:"updated_at"`
	CreateIP    string `gorm:"column:create_ip;not null" json:"create_ip"`
	LastLoginAt int32  `gorm:"column:last_login_at" json:"last_login_at"`
	LastLoginIP string `gorm:"column:last_login_ip;default:NULL" json:"last_login_ip"`
	LoginTime   int32  `gorm:"column:login_time;not null" json:"login_time"`
	UserStatus  int16  `gorm:"column:user_status;not null" json:"user_status"`
}

// TableName CrmUser's table name
func (*CrmUser) TableName() string {
	return TableNameCrmUser
}
