server:
  port: 8082
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: shopdevgo
  sslmode: disable
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  filePath: "./storages/logs/dev.001.log"
  maxSize: 500
  maxAge: 30
  maxBackups: 3
  compress: true
