server:
  port: 8082
databases:
  - user: admin
    host: localhost
    password: admin
    dbName: shopDEV
  - user: order
    host: localhost
    password: order
    dbName: shopOrderDEV
security:
  jwt:
    key: abc123
